### ISSUE TITLE
Assigning multiple processors with same extra data key to a single Logger instance

### ISSUE THREAD

**Issue by renatogcarvalho** [Seldaek/monolog#1118]
Hello folks,

In a Symfony application I'd like to share the same Monolog instance between various services that exist in a module - which I'm currently separating by a channel - and be able have a different Processor for each instance of these services. On this Processor I'm currently setting the service name in the extra data section.

Is there a way to modify an extra value on-the-fly? Or maybe removing/modifying a Processor already assigned?

I could probably simplify this by just setting the service name in the context, but I like the fact that I can control where exactly I want to show the extra data in the log message. 

Currently I was only able to accomplish this by having a whole new instance of the Logger on each service, but I wonder if there is a better way to approach this problem.

Any thoughts?

Much appreciated.

Renato.

**Comment by renatogcarvalho** [comment]
A brief example of what I'm trying to accomplish below:

```yaml
services:
    monolog.formatter.module:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.service%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"

    AppBundle\Services\Service1:
        arguments:
            - '@monolog.logger.module'

    AppBundle\Services\Service2:
        arguments:
            - '@monolog.logger.module'

monolog:
    channels:
        - module
    handlers:
        module:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.module.log'
            level: debug
            channels: [module]
            formatter: monolog.formatter.module
```

```php
<?php

namespace AppBundle\Services;

class ServiceProcessor
{
    private $fqcn;
    
    public function __construct($fqcn)
    {
        $this->fqcn = $fqcn;
    }
    
    public function __invoke(array $record): array
    {
        $record['extra']['service'] = $this->fqcn;
    
        return $record;
    }
    
    public function getFqcn(): string
    {
        return $this->fqcn;
    }
}
```

```php
<?php

namespace AppBundle\Services;

class Service1
{
    private $logger;
    
    public function __construct(\Monolog\Logger $logger) {
        $this->logger = $logger;
    
        $this->logger->pushProcessor(new ModuleProcessor(self::class));
    }
}

class Service2
{
    private $logger;
    
    public function __construct(\Monolog\Logger $logger) {
        $this->logger = $logger;
    
        $this->logger->pushProcessor(new ModuleProcessor(self::class));
    }
}
```

With this setup, my "module.log" stream I will only output "AppBundle\Services\Service1" in the extra data reserved for the FQCN.

However, if I modify my services slightly as it follows:

```php
<?php

namespace AppBundle\Services;

class Service1
{
    private $logger;
    
    public function __construct(\Monolog\Logger $logger) {
        $this->logger = clone $logger;
    
        $this->logger->pushProcessor(new ModuleProcessor(self::class));
    }
}

class Service2
{
    private $logger;
    
    public function __construct(\Monolog\Logger $logger) {
        $this->logger = clone $logger;
    
        $this->logger->pushProcessor(new ModuleProcessor(self::class));
    }
}
```
Since I now have a new instance of the Logger on each service (hence cloned) the log message contains the FQCN of each service as expected.

Would there be better way to accomplish this? I'm just concerned if multiple instances of the Logger might degrade the performance in the application.

Renato.
