### ISSUE TITLE
SlackHandler : ways to format notification

### ISSUE THREAD

**Issue by FradiFrad** [Seldaek/monolog#1181]
Hi,

On a Symfony 3.4 project, I want to send notifications to a Slack channel via Monolog. I use the SlackHandler and it works well but now I want to find a way to format my notification, using [Slack's recommendations](https://api.slack.com/docs/messages). Is it possible ?

For now, each key I send is a new field title and each value associated is a field. Can I directly change the content of "Message" ? Can I also hide the "Level" entry ? I try to use 'fields' from $attachment in SlackRecord.php, but no success so far.

Many, many thanks.

 Extracts of what I've done so far :

```
# monolog.yml
reviews:
            type: slack
            token: '%token%'
            channel: "#mychannel"
            bot_name: 'My bot'
            icon_emoji: :sports_medal:
            level: info
            channels: [reviews]
            include_extra: true
```

```
// mycontroller.php

// ...

$message = [
    'a' => $post->getTitle(),
    'b' => $ur->getInterventionRating(),
    "fields" => [
                 "title": "Priority",
                    "value": "High",
                    "short": false ], ];

$this->container->get('monolog.logger.myChannel')->info("test", $message);
```
