### ISSUE TITLE
log files not written in dev environment

### ISSUE THREAD

**Issue by PaddyLock** [Seldaek/monolog#1285]
I have the latest install of symfony 4.2 using flex and symfony/monolog-bundle": "^3.3"
Log files write correctly on production but not on my local dev environment. The config for dev is:

```
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
```

If I delete the var/log folder and then trigger the logger it does not get recreated.
If I change override the log directory in Kernel.php to /var/local/log and then trigger the logger the folder gets created but no log file.
