### ISSUE TITLE
Level is not being read from config for custom handler

### ISSUE THREAD

**Issue by wildcard27** [Seldaek/monolog#1378]
I am using Monolog version 1 with Symfony.

I'm not sure that this should be asked here or in the Symfony repo but will ask here first.

I have created a custom handler to push logs to AWS Firehose. Here is the constructor:

```
class FirehoseLogHandler extends AbstractProcessingHandler {

public function __construct(
        FirehoseClient $firehoseClient,
        FormatterInterface $formatter,
        $streamName,
        $level = Logger::INFO,
        $bubble = true
    ) {

        $this->firehoseClient = $firehoseClient;
        $this->streamName = $streamName;
        $this->formatter = $formatter;

        parent::__construct($level, $bubble);
    }
```

And here is my `monolog.yaml` config:

```
monolog:
  handlers:
    firehose_handler:
      type: service
      id: kinesis_stream_handler

    main:
      type: stream
      handler: firehose_handler
      level: error
      channels: ["!event"]

services:
  kinesis_stream_handler:
    class: App\Logger\Handler\FirehoseLogHandler
    arguments:
      $firehoseClient: '@aws.firehose'
      $formatter: '@App\Logger\Formatter\FirehoseLogFormatter'
      $streamName: 'firehose-stream-test'
```

The problem that I am having is that the `$level` is always set to `Logger::INFO` (200), or whatever is set in the constructor. It seems to be ignoring what is set in the yaml config

**Comment by alexandrmazur96** [comment]
Hi!

I think it happens because you do not pass the `level` parameter to `firehose_handler`.

As Symfony docs say:

> This defines a stack of handlers and each handler is called in the order that it's defined.

But I can be wrong with this. Try to add `level: error`:

```
monolog:
  handlers:
    firehose_handler:
      type: service
      id: kinesis_stream_handler
      level: error
```
