### ISSUE TITLE
Is it possible to set maxium logging level?

### ISSUE THREAD

**Issue by imaegoo** [Seldaek/monolog#1455]
Monolog version 1.25.3

----

Hi,

I am using monolog in **Drupal**. I am finding a way to print `info` & `warn` log to `stdout`, and print `error` log to `stderr`, if I configure 2 handlers, `error` log will appear in both `stdout` and `stderr`, that's not what I expected, `error` log should not print to `stdout`.

Here is what I configured.

```
services:
  # Monolog handlers.
  # https://github.com/Seldaek/monolog/blob/1.25.3/README.md
  monolog.handler.std_info:
    class: Monolog\Handler\StreamHandler
    arguments: ['php://stdout', '%monolog.level.info%']
  monolog.handler.std_error:
    class: Monolog\Handler\StreamHandler
    arguments: ['php://stderr', '%monolog.level.error%']
```

The [StreamHandler](https://github.com/Seldaek/monolog/blob/1.25.3/src/Monolog/Handler/StreamHandler.php) only accept minimum logging level.

```
/**
 * @param string|int $level The minimum logging level at which this handler will be triggered
 */
```

**Is it possible to set maxium logging level?**

Thanks.
