### ISSUE TITLE
Fatal error Attempted to load class "MongoClient" from the global namespace

### ISSUE THREAD

**Issue by cimo23** [Seldaek/monolog#1558]
bug occur when we use the configuration without ODM Id Service
#1423 

```
monolog:
    handlers:
        main:
            type: mongo
            mongo:
               host: '127.0.0.1'
               port: 27017
               user: root
               pass: '123456'
               database: logsDb
               collection: logsCollection
```
