### ISSUE TITLE
Monolog 3 outputs multiple log records on the same line

### ISSUE THREAD

**Issue by alexpozzi** [Seldaek/monolog#1817]
Monolog version 3

I recently upgraded to Monolog version 3 (from version 2).
I noticed that, after the upgrade, log messages seems to be outputted all together (on a single line) per request.

I'm gonna try to explain myself better.
Before, I was having a single line per log record:
```json
{"level":"INFO","message":"Request 1 - Log record 1","context":{}}
{"level":"INFO","message":"Request 1 - Log record 2","context":{}}
{"level":"ERROR","message":"Request 1 - Log record 3","context":{}}
{"level":"INFO","message":"Request 2 - Log record 1","context":{}}
{"level":"ERROR","message":"Request 2 - Log record 2","context":{}}
```
Now I get:
```json
{"level":"INFO","message":"Request 1 - Log record 1","context":{}}{"level":"INFO","message":"Request 1 - Log record 2","context":{}}{"level":"ERROR","message":"Request 1 - Log record 3","context":{}}
{"level":"INFO","message":"Request 2 - Log record 1","context":{}}{"level":"ERROR","message":"Request 2 - Log record 2","context":{}}
```

My Monolog configuration didn't change and the relevant part resembles to something like:
```yaml
monolog:
    channels:
        ...
    handlers:
        fingers_crossed_json:
            type: fingers_crossed
            action_level: error
            handler: json
            excluded_http_codes: [...]
        json:
            type: stream
            level: INFO
            path: '%env(LOG_PATH)%'
            channels: [...]
```

I tried to check on the CHANGELOG if anything could've led to this issue but nothing seemed to match.
The problem, in my case, is that this change messes up with my log data collector.

Is there a way to restore the previous behavior without downgrading?

Thank you!
