### ISSUE TITLE
GroupHandler is missing FormattableHandlerInterface

### ISSUE THREAD

**Issue by jrantwijk** [Seldaek/monolog#1824]
Monolog version 3

I'm currently getting the following error:

```
In FingersCrossedHandler.php line 240:
 The nested handler of type Monolog\Handler\WhatFailureGroupHandler does not support formatters
```

It seems like the parent GroupHandler class is missing the `FormattableHandlerInterface`.

**Comment by mazumba** [comment]
I recently stumbled across the same issue, but after trying to create a PR for this, I realised that we maybe have it backwards.

Somebody correct me if I'm wrong, but I  think this works as intended. The `FingersCrossedHandler` is a wrapper that should not be used to wrap GroupHandlers but should wrap an `AbstractProcessingHandler` directly and "nest" the `FingersCrossedHandler` into the `WhatFailureGroupHandler` instead.

So a correct example configuration in yaml would be:
```
    monolog:
        handlers:
            main:
                type: whatfailuregroup
                members: [ nested ]
            nested:
                type: fingers_crossed
                action_level: error
                handler: stream
                excluded_http_codes: [ 404, 405 ]
            stream:
                type: stream
                path: "..."
                level: debug
                formatter: app.test_line_formatter
```
