### ISSUE TITLE
Log Message is truncated

### ISSUE THREAD

**Issue by revoltek-daniel** [Seldaek/monolog#1891]
Monolog version 2.9.3

We use Monolog in our Sylius Shop, sometimes we get Messages which are truncated.

This is how it should look:
> [2024-05-29T12:27:06.472277+02:00] saferpay.DEBUG: Webhook handled successfully [] []
[2024-05-29T12:27:13.159350+02:00] saferpay.DEBUG: Handling webhook started [] []
[2024-05-29T12:27:13.163790+02:00] saferpay.DEBUG: PrepareCaptureAction: Synchronous processing started [] []
[2024-05-29T12:27:13.177069+02:00] saferpay.DEBUG: Synchronous processing PrepareCaptureAction succeeded [] []

Log file output:
> [2024-05-29T12:27:13.793507+02:00] saferpay.DEBUG: Webhook handled successfully [] []
ous processing PrepareAssertAction succeeded [] []
[2024-05-29T12:27:14.063790+02:00] saferpay.DEBUG: PrepareCaptureAction: Synchronous processing started [] []

Monolog config:
```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
        saferpay:
            type: rotating_file
            path: "%kernel.logs_dir%/saferpay.log"
            level: debug
            channels: ["saferpay"]
            max_files: 90
```

Is this a bug or have we done something wrong with our configuration?
