### ISSUE TITLE
Curl error when leaving webhookurl empty

### ISSUE THREAD

**Issue by Jalliuz** [Seldaek/monolog#1931]
We have a Monolog/Slack "webhook" implementation in our project. It works fine except when you don't have a webhook url

In my local environment I don't immediately have a Slack webhookurl. These are managed by Slack admins of our company so I can't just create one myself.

But the project requires one in the monolog config.
````
monolog:
    channels:
        - slack_error
    handlers:
        slack_error:
            type: slackwebhook
            webhook_url: '%env(SLACK_ERROR_WEBHOOK_URL)%'
            channel: '%env(SLACK_ERROR_CHANNEL)%'
            bot_name: '%env(SLACK_BOT_NAME)%'
            icon_emoji: '%env(SLACK_EMOJI)%'
            level: '%env(SLACK_ERROR_LEVEL)%'
            include_extra: true
````
If I leave it empty, my whole project crashes with a curl error in Handler/SlackWebhookHandler.php line 110

Is there an option to disable it?

What I currently did is setting the level
`level: emergency`
This is the highest level and I guess it currently never gets thrown.

Solution:
A solution for this bundle can be that if the webhookurl is left empty, no curl will get called

Another solution is adding an option
`enabled: false`

So te developer can decide if its enabled in his environment or not
