### ISSUE TITLE
Add support for handling PHP Errors, etc

### ISSUE THREAD

**Issue by davidwindell** [Seldaek/monolog#199]
Examples of this are in Zend\Log and Raven_Client

https://github.com/getsentry/raven-php/blob/master/lib/Raven/ErrorHandler.php
(Handles uncaught exceptions, fatal errors and PHP errors)

https://github.com/zendframework/zf2/blob/master/library/Zend/Log/Logger.php#L504

**Comment by greg0ire** [comment]
How can I use the fatal error handler in a symfony2 application ? I couldn't find anything about `registerShutdownFunction` in the monolog bundle, and I would like to be able to send fatal error reports to sentry.

**Comment by stof** [comment]
@greg0ire Symfony registers its own error handler for fatal errors (in which it calls the logger too)

**Comment by greg0ire** [comment]
@stof : even in the production environment ? Fatal errors are not sent to sentry, that's why I ask… for instance, if I call in a random controller the `doesNotExist()` function, I can see the error in the nginx logs, but not in sentry…

**Comment by greg0ire** [comment]
I can get a fatal error in sentry by doing the following in a controller:

```php
        \Monolog\ErrorHandler::register($this->get('logger'));
        doesnotexist();
```

Is there something similar I can do in Symfony to get the same thing ? @stof : maybe this is something new ? I'm using symfony LTS (2.3), so there's that…

**Comment by Seldaek** [comment]
It's a new thing in symfony IIRC. If you use 2.3 LTS you can just register the monolog ErrorHandler in a request listener or something like that no?

**Comment by greg0ire** [comment]
@Seldaek : yes, I guess… I'll do that, thanks! I was only wondering what was the right way to do that.

**Comment by greg0ire** [comment]
Thank you , it works! Here is the code : 

```php
<?php

namespace MyCompany\AppBundle\EventListener;

use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Monolog\Logger;
use Monolog\ErrorHandler;
use Symfony\Component\HttpKernel\HttpKernelInterface;


/**
 * This should become useless when using symfony 2.7
 *
 * @see https://github.com/Seldaek/monolog/issues/199
 */
class FatalErrorHandlerListener
{
    public function __construct(Logger $logger, $isDebug)
    {
        $this->logger = $logger;
        $this->isDebug = $isDebug;
    }

    public function onKernelRequest(GetResponseEvent $event)
    {
        // register the monolog handler only when in production
        if ($event->getRequestType() == HttpKernelInterface::MASTER_REQUEST && !$this->isDebug) {
            ErrorHandler::register($this->logger);
        }
    }
}
```

```yaml
services:
    listener.fatal_error_handler:
        class: MyCompany\MyAppBundle\EventListener\FatalErrorHandlerListener
        arguments:
            - @logger
            - %kernel.debug%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
```

People using that should remember to clear their cache.
