### ISSUE TITLE
GelfHandler::write need a Interface

### ISSUE THREAD

**Issue by skydiablo** [Seldaek/monolog#418]
i want to use the "GelfHandler" in SF2 project. so i add to my composer.json:

```
"graylog2/gelf-php": "dev-master"
```

but now, if i want to log something, i get a error in GelfHandler::write()

```
Gelf\Publisher::publish() must be an instance of Gelf\MessageInterface, string given
```

what is here wrong ? my SF2 config.yml:

```
monolog:
    handlers:
        main:
            type: gelf
            publisher:
                hostname: %Graylog2.Host%
                port: %Graylog2.Port%
            level: info
            formatter: monolog.formatter.session_request
```
