### ISSUE TITLE
Monolog swiftmailer handler sends one mail per log entry

### ISSUE THREAD

**Issue by olegstepura** [Seldaek/monolog#48]
with this configuration:

```
    mail:
      type: fingers_crossed
      action_level: error
      handler: mailed
      buffer_size: 100
    mailed:
      type: swift_mailer
      from_email: error_box @ gmail.com
      to_email: error_box @ gmail.com
      subject: Errors logged
      level: debug
      formatter: my_formatter
```

seems like swiftmailer is used to send one log line per message. That is really a bad idea since
1. Some mail servers may start blocking send requests sent that often
2. Some mail servers that receive such a big amount of mail may consider it is spam
3. It creates bigger traffic and is longer to send 100 mails instead of 1

Swiftmailer handler must have some buffer to send multiple messages per mail.

@see https://groups.google.com/forum/#!topic/symfony-devs/IZ4a_-Oyt2c
