### ISSUE TITLE
Possibility to add tags to TagProcessor during runtime?

### ISSUE THREAD

**Issue by giggsey** [Seldaek/monolog#588]
I use monolog with long living processes to process events/tasks.

I'd like to be able to use the TagProcessor to store information about each event whilst processing it without having to create a new instance of TagProcessor.

The sort of thing I would like to do is:

```php
<?php

$tagger = new TagProcessor();


$logger = new Monolog;// etc
$logger->pushProcessor($tagger);
while ($event = getFromQueue()) {
    $tagger->setTags(['id' => $event->getID()]);

    // Do things...
    $logger->info('done');
}

```

**Comment by giggsey** [comment]
Thanks :)

**Comment by giggsey** [comment]
@Seldaek Why do you `array_values` on `addTags`, but the constructor and `setTags` allows you to pass a fully associative array?

**Comment by Seldaek** [comment]
Oh yeah that's something I didn't consider.. I just thought of it as a list of tags like ['foo', 'bar'] not that you would use it associatively. I'll fix that.

**Comment by giggsey** [comment]
Thanks again.

**Comment by gempir** [comment]
I have a line formatter 
```
    class: Monolog\Formatter\LineFormatter
    arguments:
      - "[%%datetime%%][%%extra.process_id%%][%%level_name%%]%%extra.tags%%[%%channel%%] %%message%% \n"
      - "Y-m-d H:i:s,v"
    calls:
      - [includeStacktraces]```
      
But it always adds quotes to my extra tags. Can that be avoided? 

I call my logger like 
      
```
$this->tagger->addTags(['js_error']);
$this->logger->error($message);
$this->tagger->setTags([]); // reset the tags
```

Resulting log line:
`[2022-01-04 12:20:05,664][29998][ERROR]["js_error"][app] foo bar`
