### ISSUE TITLE
How can I log information which level is only info?

### ISSUE THREAD

**Issue by feridmovsumov** [Seldaek/monolog#662]
webhook_consumer_error.log contains only errors but webhook_consumer_info.log contains infos and errors. I need webhook_consumer_info.log to contains only info level logs. How can I do that ?

config.php
```yml
        webhook_consumer_error:
            type: stream
            path: "%kernel.root_dir%/logs/webhook_consumer_error.log"
            level: error
            channels: [webhook_consumer]
        webhook_consumer_info:
            type: stream
            path: "%kernel.root_dir%/logs/webhook_consumer_info.log"
            level: info
            channels: [webhook_consumer]
```

services.yml
```yml
    webhook_consumer_service:
       class: ApiBundle\Command\WebhookConsumer
       arguments: [@service_container, @logger]
       tags:
            - { name: monolog.logger, channel: webhook_consumer }
```

@Seldaek

**Comment by xabbuh** [comment]
You can wrap your `webhook_consumer_info` handler in a filter handler that limits logs to the `INFO` level.

**Comment by feridmovsumov** [comment]
@xabbuh can you give an example please?

**Comment by xabbuh** [comment]
Try something like this (untested though):

```yaml
webhook_consumer_error:
    type: stream
    path: "%kernel.root_dir%/logs/webhook_consumer_error.log"
    level: error
    channels: [webhook_consumer]
webhook_consumer_info_filter:
    type: filter
    handler: webhook_consumer_info
    accepted_levels: [info]
webhook_consumer_info:
    type: stream
    path: "%kernel.root_dir%/logs/webhook_consumer_info.log"
    level: info
    channels: [webhook_consumer]
```
