### ISSUE TITLE
WebProcessor constructor logic seems weird using with Cascade

### ISSUE THREAD

**Issue by nonnenmacher** [Seldaek/monolog#663]
I'm trying to use Cascade to isolate my logger configuration in one spot.

However, when trying pass `extraFields` (e.g X-FORWARD-FOR) from Cascade config
to WebProcessor constructor seems to do the *reverse logic* from what a standard human 
can think of first !

The actual code *remove* all matching *fieldname* that is passed in the constructor argument array `$extraFields` from the *default* member `$this->extraFields`

If I use a configuration entry like 

    ```
      processors:
      monolog.processor.web:
         class: Monolog\Processor\WebProcessor
         extra_fields:
             url: REQUEST_URI
             forwarded: REMOTE_ADDR
    ```

The current code (at end of constructor) read as

```php
        if (null !== $extraFields) {
            foreach (array_keys($this->extraFields) as $fieldName) {
                if (!in_array($fieldName, $extraFields)) {
                    unset($this->extraFields[$fieldName]);
                }
            }
        }
```

and end with the `url` entry removed from the `$this->extraFields` and no *added* extra entry for `forwarded` stuffed into the record['extra'] when adorning the log entry.

However with the following code modifications
 
```php
      if (null !== $extraFields) {
            foreach ($extraFields as $extraName => $serverName) {
                if (!in_array($extraName, $this->extraFields)) {
                    $this->addExtraField($extraName,$serverName);
                }
            }
        }
```

Everything sound fine.

No extra field with same name and all provided `name` to `server var` is mapped properly.

Is this is a bug or a feature that I do not use as intended ??
