### ISSUE TITLE
facility LOG_LOCAL4 in yml config

### ISSUE THREAD

**Issue by christophe-mailfert** [Seldaek/monolog#684]
In my project i try to put syslog logger with facility LOG_LOCAL4: 
```
monolog:
    handlers:
        syslog:
            type: syslog
            facility: LOG_LOCAL4
            level: ERROR
            formatter: mycrm.log.formatter
```

but monolog think it's a string "LOG_LOCAL4", How can i resolve this one ?
