### ISSUE TITLE
SlackHandler ignores includeStacktraces

### ISSUE THREAD

**Issue by websirnik** [Seldaek/monolog#745]
I'm using MonologBundle to include stacktraces in logs. It works for StreamHandler, but not for Slack.

``` yaml
monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: error
            include_stacktraces: true
        slack:
            type: slack
            token: xxx
            channel: "#errors"
            bot_name: ErrorBot
            icon_emoji: :ghost:
            level: critical
            include_stacktraces: true
```
