### ISSUE TITLE
chromephp shows messages twice on console

### ISSUE THREAD

**Issue by tarlepp** [Seldaek/monolog#766]
For some reason if I use chromephp it shows log messages twice. I also checked that log file contains that info just once and same with firephp.

**Comment by Seldaek** [comment]
What handlers do you have defined? Maybe you have two different ones doing the same? Or the same handler twice somehow? Because otherwise I don't see how this would happen.

**Comment by tarlepp** [comment]
here is my config for handlers:

```
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
            formatter: app.monolog_formatter
        console:
            type: console
            channels: [!event, !doctrine]
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info
```

And if I remove that chromephp part, none of logs are coming to my chrome console.
