### ISSUE TITLE
Not compatible with Rollbar v1

### ISSUE THREAD

**Issue by ebuildy** [Seldaek/monolog#980]
Looks like Rollbar team have refactored the library:

https://github.com/rollbar/rollbar-php/releases/tag/v1.0.0

RollbarNotifier has gone :/

**Comment by elazar** [comment]
Rollbar added a PSR-3 logger in 1.0. You can integrate it with Monolog [like so](https://github.com/rollbar/rollbar-php#using-monolog). I think this issue can be closed.

**Comment by ebuildy** [comment]
why closed ? heu, the code here https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RollbarHandler.php is wrong with latest Rollbar, this is what I mean.

**Comment by stof** [comment]
@ebuildy as Rollbar 1 contains a PSR-3 implementation, you can use the PsrHandler of Monolog (putting the Rollbar class inside it) instead of using RollbarHandler (which was indeed written for 0.x versions)

**Comment by alister** [comment]
What is the configuration required in MonologBundle to enable Rollbar v1+ to be wrapped into a PsrHandler?

**Comment by Seldaek** [comment]
IMO the best would be to do something like this in the bundle config:

```php
$config = array(
    'access_token' => '$rollbar_token',
    'minimumLevel' => 'error',
);
$handler = new \Monolog\Handler\PsrHandler(new \Rollbar\RollbarLogger($config));
```

**Comment by cordoval** [comment]
This does not work well because the wrapping it with PSR does not pass exceptions trace in the right way to the library. I have solved this with a proper handler but I think we should just stick with what we have and let the user define its own custom services. But yes discourage from the usage above since it is not optimal.

**Comment by aurelijusrozenas** [comment]
My symfony 3 handler version, working with custom and person data, tested with rollbar v1.3.2 and monolog 1.23.0. Some custom app implementation is left, but I cleaned it more or less. This is PHP 7.1 version so for lower versions argument and return types should be removed and other minor changes might be required. Spent some time tweaking it to get working so I thought it's worth sharing.

```yaml
# loggers.yml
services:
    app.logger.handler.rollbar:
        class: AppBundle\Monolog\RollbarHandler
        arguments:
            - '@service_container'
            - '@app.logger.rollbar'
    app.logger.rollbar:
        class: Rollbar\RollbarLogger
        arguments:
            -
                access_token: '%rollbar_token%'
                environment: '%kernel.environment%'
                # for some reason this custom must be defined here, otherwise custom data will not be passed to rollbar
                custom: []
```
```yaml
# config_prod.yml
monolog:
    handlers:
        handler_error:
            type:         fingers_crossed
            action_level: error
            handler:      grouped_error
        grouped_error:
            type:    whatfailuregroup
            members: [streamed, rollbar]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        rollbar:
            type: service
            # note: level may be set in service definition 'loggers.yml'
            id: app.logger.handler.rollbar
```
```php
// AppBundle/Monolog/RollbarHandler.php
namespace AppBundle\Monolog;

use AppBundle\Entity\User;
use AppBundle\Exceptions\ExceptionWithContextException;
use Monolog\Handler\AbstractHandler;
use Monolog\Logger;
use Rollbar\RollbarLogger;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Security\Core\User\UserInterface;

class RollbarHandler extends AbstractHandler
{
    /** @var bool */
    private $hasRecords;
    /** @var RollbarLogger */
    private $rollbarLogger;
    /** @var ContainerInterface */
    private $container;

    /**
     * @param ContainerInterface $container it's bad practice to inject container, but let's not risk circular injection problems
     * @param RollbarLogger      $logger
     * @param int                $level
     * @param bool               $bubble
     */
    public function __construct(ContainerInterface $container, RollbarLogger $logger, $level = Logger::ERROR, $bubble = true)
    {
        parent::__construct($level, $bubble);

        $this->rollbarLogger = $logger;
        $this->container = $container;
    }

    public function handle(array $record): bool
    {
        if (!$this->isHandling($record)) {
            return false;
        }

        $record = $this->processRecord($record);
        // pass person data
        $this->rollbarLogger->configure(['person' => $this->getPersonData()]);

        $this->hasRecords = true;
        $this->rollbarLogger->log(strtolower($record['level_name']), $record['message'], $record['context']);

        return false === $this->bubble;
    }

    public function isHandling(array $record): bool
    {
        $isHandling = parent::isHandling($record);

        if ($isHandling && $this->isSkipping($record)) {
            return false;
        }

        return $isHandling;
    }


    public function close()
    {
        $this->flush();
    }

    private function flush()
    {
        if ($this->hasRecords) {
            $this->rollbarLogger->flush();
            $this->hasRecords = false;
        }
    }

    private function processRecord(array $record): array
    {
        // while unlikely, but ['context'] may not be set
        $record['context'] = $record['context'] ?? [];

        $exception = $this->getException($record);
        // uncaught exception
        if ($exception) {
            // must be set, produces different rollbar message and displays exception trace
            $record['message'] = $exception;
        } // manual log(error/critical/etc.) called
        else {
            // add stack trace as custom data because it is not clear how to pass it as exception stack trace
            $stackTrace = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT | DEBUG_BACKTRACE_IGNORE_ARGS);
            $record['context'] = array_merge($record['context'], self::getFormattedStackTrace($stackTrace));
        }
        // custom data may be passed though exception
        if ($exception instanceof ExceptionWithContextException) {
            $record['context'] = array_merge($record['context'], $exception->getContext());
        }

        return $record;
    }

    private function getPersonData(): array
    {
        $personData = [];
        $user = $this->getUser();
        if ($user instanceof User) {
            $personData = array_merge($personData, [
                'id' => $user->getId(),
                'username' => $user->getUsername(),
                'email' => $user->getEmail(),
            ]);
        } // Send user email on unsent registration confirmation
        elseif (isset($_POST['fos_user_registration_form']['email'])) {
            $email = $_POST['fos_user_registration_form']['email'];
            $personData = array_merge($personData, [
                'id' => $email,
                'username' => $email,
                'email' => $email,
            ]);
        }

        return $personData;
    }

    private function getUser(): ?UserInterface
    {
        $user = null;
        if ($this->getTokenStorage()->getToken()) {
            $user = $this->getTokenStorage()->getToken()->getUser();
            // this may string 'anon.'
            if (!is_object($user)) {
                $user = null;
            }
        }

        return $user;
    }

    private function isSkipping(array $record): bool
    {
        $isSkipping = false;

        $exception = $this->getException($record);
        if (0 /* custom logic */) {
            $isSkipping = true;
        }

        return $isSkipping;
    }

    /**
     * It's not pretty, but it helps, OK?
     *
     * @param array $stackTrace
     *
     * @return array
     */
    private static function getFormattedStackTrace(array $stackTrace): array
    {
        $stackTraceFormatted = [];

        // borrowed from \Rollbar\DataBuilder::makeFrames
        foreach ($stackTrace as $key => $item) {
            $filename = $item['file'] ?? '<internal>';
            $lineNo = $item['line'] ?? 0;
            $method = $item['function'];
            if (isset($item['class'])) {
                $method = $item['class'].'::'.$method;
            }

            $message = sprintf(
                'File "%s" line %d in %s',
                $filename,
                $lineNo,
                $method
            );

            $stackTraceFormatted['stack_trace_'.$key] = mb_ucfirst($message);
        }

        return $stackTraceFormatted;
    }

    private function getException(array $record): ?\Exception
    {
        return $record['context']['exception'] ?? null;
    }

    private function getTokenStorage(): \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
    {
        return $this->container->get('security.token_storage');
    }
}
```
